#!/bin/bash -e

ORG_PATH="${ORG_PATH:-github.com/coreos}"
REPO_PATH="${REPO_PATH:-${ORG_PATH}/mayday}"

if [ ! -h gopath/src/${REPO_PATH} ]; then
	mkdir -p gopath/src/${ORG_PATH}
	ln -s ../../../.. gopath/src/${REPO_PATH} || exit 255
fi

export GOBIN=${PWD}/bin

eval $(go env)

echo "Building mayday..."
go build -o bin/mayday ${REPO_PATH}
