#!/bin/bash -e
#
# Run all fleet tests (not including functional)
#   ./test
#   ./test -v
#
# Run tests for one package
#   PKG=./unit ./test
#   PKG=ssh ./test
#

source ./build

echo "Running tests..."

if [[ $* == *--coverprofile* ]]; then
	# generate html cover document
	mkdir -p tmp/
	go test github.com/coreos/mayday/mayday -coverprofile tmp/mayday.out
	go test github.com/coreos/mayday -coverprofile tmp/main.out
	go tool cover -html=tmp/mayday.out -o tmp/mayday.html
	go tool cover -html=tmp/main.out -o tmp/main.html
else
	# just report percentage
	go test ./... -cover
fi

echo "Checking gofmt..."
fmtRes=$(gofmt -l .)
if [ -n "${fmtRes}" ]; then
	echo -e "gofmt checking failed:\n${fmtRes}"
	exit 255
fi

echo "Success"
